api-url: http://openfga:8080
model-id: 01KXNZQ9BGDHVYZHSZP9XEPF6F
store-id: 01KXNYZJ8QJJVHG9PXY9CFARBM

# Auth stuff I'm not using yet
# client-id: <...>
# client-secret: <...>
# api-audience: <...>
# api-token-issuer: <...>
